-- Canonical openIMIS reference data (system roles, role-rights, registers).
-- Ported from openimis/database_ms_sqlserver sql/base/5_base_data.sql (T-SQL -> PG,
-- type-aware boolean casts, idempotent ON CONFLICT DO NOTHING).
-- EXCLUDED on purpose: tblUsers/tblUsersDistricts/tblUserRole seed rows (known default
-- credentials), tblLocations demo rows (Egypt governorates come from egypt_localization),
-- tblIMISDefaults*. ICD-10 register ships empty: load WHO ICD-10 as an operational step.
INSERT INTO "tblConfirmationTypes" ("ConfirmationTypeCode", "ConfirmationType", "SortOrder", "AltLanguage") VALUES ('A', 'Local council', NULL, 'Conseil local') ON CONFLICT DO NOTHING;
INSERT INTO "tblConfirmationTypes" ("ConfirmationTypeCode", "ConfirmationType", "SortOrder", "AltLanguage") VALUES ('B', 'Municipality', NULL, 'Municipalité') ON CONFLICT DO NOTHING;
INSERT INTO "tblConfirmationTypes" ("ConfirmationTypeCode", "ConfirmationType", "SortOrder", "AltLanguage") VALUES ('C', 'State', NULL, 'Etat') ON CONFLICT DO NOTHING;
INSERT INTO "tblConfirmationTypes" ("ConfirmationTypeCode", "ConfirmationType", "SortOrder", "AltLanguage") VALUES ('D', 'Other', NULL, 'Autre') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Age', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('AntenatalAmountLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ApprovalOfSMS', 'N', 'Family') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('BeneficiaryCard', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Ceiling1', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Ceiling2', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('CHFID', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ClaimAdministrator', 'M', 'FindClaim, Claim, ClaimReview, ClaimFeedback') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Confirmation', 'O', 'Family, Insuree, OverviewFamily, ChangeFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ConfirmationNo', 'O', 'Family, Insuree, FindFamily, OverviewFamily, ChangeFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ConsultationAmountLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ContributionCategory', 'O', 'Premium, FindPremium') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('CurrentAddress', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('CurrentDistrict', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('CurrentMunicipality', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('CurrentVillage', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Ded1', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Ded2', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('DeliveryAmountLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('DistrictOfFSP', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('DOB', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Education', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ExpiryDate', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('FamilyType', 'O', 'Family, ChangeFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('FirstServicePoint', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('FSP', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('FSPCategory', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('FSPDistrict', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Gender', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('GuaranteeNo', 'O', 'Claim, ClaimReview') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('HFLevel', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('HospitalizationAmountLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('IdentificationNumber', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('IdentificationType', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('InsureeEmail', 'O', 'Family, Insuree, FindFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('LastName', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblItemCode', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblItemCodeL', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblItemLeftL', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblItemMinDate', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblServiceLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('lblServiceMinDate', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('MaritalStatus', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('OtherNames', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('PermanentAddress', 'O', 'Family, Insuree, ChangeFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('PolicyStatus', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Poverty', 'O', 'Family, Insuree, Policy, Premium, FindFamily, ChangeFamily') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('ProductCode', 'M', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Profession', 'O', 'Family, Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('RegionOfFSP', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Relationship', 'O', 'Insuree') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('SurgeryAmountLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalAdmissionsLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalAmount', 'N', 'AppPolicies') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalAntenatalLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalConsultationsLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalDelivieriesLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalSurgeriesLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('TotalVisitsLeft', 'O', 'Search Insurance Number/Enquiry') ON CONFLICT DO NOTHING;
INSERT INTO "tblControls" ("FieldName", "Adjustibility", "Usage") VALUES ('Vulnerability', 'O', 'Insuree, Family') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (1, 'Nursery', NULL, 'Garderie') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (2, 'Primary school', NULL, 'École primaire') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (3, 'Secondary school', NULL, 'École secondaire') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (4, 'University', NULL, 'Université') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (5, 'Postgraduate studies', NULL, 'Études supérieures') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (6, 'PHD', NULL, 'Doctorat') ON CONFLICT DO NOTHING;
INSERT INTO "tblEducations" ("EducationId", "Education", "SortOrder", "AltLanguage") VALUES (7, 'Other', NULL, 'Autre') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('C', 'Council', NULL, 'Conseil') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('G', 'Organization', NULL, 'Organisation') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('H', 'Household', NULL, 'Ménage') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('O', 'Other', NULL, 'Autre') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('P', 'Priests', NULL, 'Prètres') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('S', 'Students', NULL, 'Etudiants') ON CONFLICT DO NOTHING;
INSERT INTO "tblFamilyTypes" ("FamilyTypeCode", "FamilyType", "SortOrder", "AltLanguage") VALUES ('T', 'Teachers', NULL, 'Enseignant') ON CONFLICT DO NOTHING;
INSERT INTO "tblGender" ("Code", "Gender", "AltLanguage", "SortOrder") VALUES ('F', 'Female', 'Femme', 2) ON CONFLICT DO NOTHING;
INSERT INTO "tblGender" ("Code", "Gender", "AltLanguage", "SortOrder") VALUES ('M', 'Male', 'Homme', 1) ON CONFLICT DO NOTHING;
INSERT INTO "tblGender" ("Code", "Gender", "AltLanguage", "SortOrder") VALUES ('O', 'Other', 'Autre', 3) ON CONFLICT DO NOTHING;
INSERT INTO "tblIdentificationTypes" ("IdentificationCode", "IdentificationTypes", "AltLanguage", "SortOrder") VALUES ('D', 'Driver''s License', 'Permis de conduire', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblIdentificationTypes" ("IdentificationCode", "IdentificationTypes", "AltLanguage", "SortOrder") VALUES ('N', 'National ID', 'Carte d''identité', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblIdentificationTypes" ("IdentificationCode", "IdentificationTypes", "AltLanguage", "SortOrder") VALUES ('P', 'Passport', 'Passeport', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblIdentificationTypes" ("IdentificationCode", "IdentificationTypes", "AltLanguage", "SortOrder") VALUES ('V', 'Voter Card', 'Carte d''électeur', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblLanguages" ("LanguageCode", "LanguageName", "SortOrder") VALUES ('fr', 'Français', 2) ON CONFLICT DO NOTHING;
INSERT INTO "tblLegalForms" ("LegalFormCode", "LegalForms", "SortOrder", "AltLanguage") VALUES ('C', 'Charity', NULL, 'Charité') ON CONFLICT DO NOTHING;
INSERT INTO "tblLegalForms" ("LegalFormCode", "LegalForms", "SortOrder", "AltLanguage") VALUES ('D', 'District organization', NULL, 'Organisation du district') ON CONFLICT DO NOTHING;
INSERT INTO "tblLegalForms" ("LegalFormCode", "LegalForms", "SortOrder", "AltLanguage") VALUES ('G', 'Government', NULL, 'Gouvernement') ON CONFLICT DO NOTHING;
INSERT INTO "tblLegalForms" ("LegalFormCode", "LegalForms", "SortOrder", "AltLanguage") VALUES ('P', 'Private organization', NULL, 'Organisation privée') ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('C', 'Co-operative', 'Coopérative', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('D', 'Donor', 'Donateur', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('G', 'Government', 'Gouvernement', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('L', 'Local Authority', 'Autorité locale', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('O', 'Other', 'Autre', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblPayerType" ("Code", "PayerType", "AltLanguage", "SortOrder") VALUES ('P', 'Private Organization', 'Organisation privée', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "SortOrder", "AltLanguage") VALUES (1, 'Housewife', NULL, 'Femme au foyer') ON CONFLICT DO NOTHING;
INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "SortOrder", "AltLanguage") VALUES (2, 'Employee', NULL, 'Employé') ON CONFLICT DO NOTHING;
INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "SortOrder", "AltLanguage") VALUES (3, 'Self Employee', NULL, 'Indépendant') ON CONFLICT DO NOTHING;
INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "SortOrder", "AltLanguage") VALUES (4, 'Others', NULL, 'Autres') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (1, 'Brother/Sister', NULL, 'Frère/soeur') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (2, 'Father/Mother', NULL, 'Père/Mère') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (3, 'Uncle/Aunt', NULL, 'Oncle/tante') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (4, 'Son/Daughter', NULL, 'Fils/fille') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (5, 'Grand parents', NULL, 'Grands/parents') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (6, 'Employee', NULL, 'Employé') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (7, 'Others', NULL, 'Autres') ON CONFLICT DO NOTHING;
INSERT INTO "tblRelations" ("RelationId", "Relation", "SortOrder", "AltLanguage") VALUES (8, 'Spouse', NULL, 'Époux') ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (1, gen_random_uuid(), 'Enrolment Officer', 'Agents d''affiliation', 1, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (2, gen_random_uuid(), 'Manager', 'Manager', 2, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (3, gen_random_uuid(), 'Accountant', 'Comptable', 4, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (4, gen_random_uuid(), 'Clerk', 'Employé de bureau', 8, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (5, gen_random_uuid(), 'Medical Officer', 'Médecin', 16, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (6, gen_random_uuid(), 'Scheme Administrator', 'Administrateur du régime d''assurance', 32, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (7, gen_random_uuid(), 'IMIS Administrator', 'Gestionnaire IMIS', 64, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (8, gen_random_uuid(), 'Receptionist', 'Réceptionniste', 128, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (9, gen_random_uuid(), 'Claim Administrator', 'Gestionnaire de remboursement', 256, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (10, gen_random_uuid(), 'Claim Contributor', 'Contributeur de remboursement', 512, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (11, gen_random_uuid(), 'HF Administrator', 'Gestionnaire d''établissement de santé', 524288, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRole" ("RoleID", "RoleUUID", "RoleName", "AltLanguage", "IsSystem", "IsBlocked", "ValidityFrom", "ValidityTo", "AuditUserID", "LegacyID") VALUES (12, gen_random_uuid(), 'Offline Administrator', 'Administrateur Offline', 1048576, false, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (1, 1, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (2, 1, 101002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (3, 1, 101003, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (4, 1, 101004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (5, 1, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (6, 1, 101102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (7, 1, 101103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (8, 1, 101104, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (9, 1, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (10, 1, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (11, 1, 101202, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (12, 1, 101203, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (13, 1, 101204, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (14, 1, 101205, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (15, 1, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (16, 1, 101302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (17, 1, 101303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (18, 1, 101304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (19, 1, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (20, 1, 111009, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (21, 6, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (22, 6, 121001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (23, 6, 121002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (24, 6, 121003, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (25, 6, 121004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (26, 6, 121005, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (27, 6, 121101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (28, 6, 121102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (29, 6, 121103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (30, 6, 121104, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (31, 6, 121201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (32, 6, 121202, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (33, 6, 121203, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (34, 6, 121204, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (35, 6, 121205, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (36, 6, 121301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (37, 6, 121302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (38, 6, 121303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (39, 6, 121304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (40, 6, 121305, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (41, 6, 121401, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (42, 6, 121402, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (43, 6, 121403, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (44, 6, 121404, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (45, 6, 122101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (46, 6, 122102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (47, 6, 122103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (48, 6, 122104, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (49, 6, 121501, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (50, 6, 121502, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (51, 6, 121503, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (52, 6, 121504, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (53, 6, 121601, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (54, 6, 121602, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (55, 6, 121603, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (56, 6, 121604, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (57, 6, 121801, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (58, 6, 121802, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (59, 6, 121803, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (60, 6, 121804, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (61, 6, 131001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (62, 6, 131002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (63, 6, 131003, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (64, 6, 131004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (65, 6, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (66, 6, 131102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (67, 6, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (68, 6, 131104, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (69, 6, 131105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (70, 6, 131106, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (71, 6, 131209, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (72, 7, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (73, 7, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (74, 7, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (75, 7, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (76, 7, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (77, 7, 121901, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (78, 7, 121902, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (79, 7, 121903, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (80, 7, 121904, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (81, 7, 121905, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (82, 7, 131005, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (83, 7, 131006, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (84, 7, 131207, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (85, 7, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (86, 7, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (87, 7, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (88, 7, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (89, 7, 122000, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (90, 7, 122001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (91, 7, 122002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (92, 7, 122003, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (93, 7, 122004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (94, 7, 122005, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (95, 3, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (96, 3, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (97, 3, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (98, 3, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (99, 3, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (100, 3, 101401, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (101, 3, 101402, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (102, 3, 101403, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (103, 3, 101404, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (104, 3, 111101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (105, 3, 111102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (106, 3, 111103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (107, 3, 131204, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (108, 3, 131205, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (109, 3, 131206, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (110, 3, 131210, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (111, 3, 131211, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (112, 3, 131212, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (113, 3, 131213, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (114, 3, 131214, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (115, 3, 131215, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (116, 3, 131216, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (117, 3, 131217, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (118, 3, 131218, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (119, 3, 131219, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (120, 3, 131220, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (121, 3, 131221, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (122, 3, 131222, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (123, 3, 131401, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (124, 9, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (125, 9, 111002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (126, 9, 111004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (127, 9, 111005, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (128, 9, 111006, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (129, 9, 111007, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (130, 4, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (131, 4, 101002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (132, 4, 101003, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (133, 4, 101004, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (134, 4, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (135, 4, 101102, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (136, 4, 101103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (137, 4, 101104, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (138, 4, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (139, 4, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (140, 4, 101202, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (141, 4, 101203, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (142, 4, 101204, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (143, 4, 101205, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (144, 4, 101301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (145, 4, 101302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (146, 4, 101303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (147, 4, 101304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (148, 2, 131201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (149, 2, 131202, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (150, 2, 131203, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (151, 2, 131208, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (152, 2, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (153, 5, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (154, 5, 111008, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (155, 5, 111009, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (156, 5, 111010, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (157, 5, 111011, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (158, 5, 131223, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (159, 8, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (160, 8, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (161, 8, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (162, 8, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (163, 10, 111001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (164, 10, 111002, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (165, 10, 111005, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (166, 12, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (167, 12, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (168, 12, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (169, 12, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (170, 12, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (171, 12, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (172, 12, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (173, 12, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (174, 12, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (175, 12, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (176, 11, 121701, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (177, 11, 121702, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (178, 11, 121703, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (179, 11, 121704, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (180, 11, 131101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (181, 11, 131103, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (182, 11, 131301, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (183, 11, 131302, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (184, 11, 131303, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (185, 11, 131304, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (186, 9, 101105, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (187, 1, 131200, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (188, 1, 131201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (189, 9, 101001, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (190, 9, 101101, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (191, 9, 101201, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (192, 9, 111012, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tblRoleRight" ("RoleRightID", "RoleID", "RightID", "ValidityFrom", "ValidityTo", "AuditUserId", "LegacyID") VALUES (193, 6, 131107, CURRENT_TIMESTAMP, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
